language:
  - cpp

# why does Travis not allow for multi-dimensional build matrices?!?
#  -> https://github.com/travis-ci/travis-ci/issues/1519
env:
  matrix:
    - CMAKE_BUILD_TYPE="Release" WITH_MPI=OFF CXX=clang++
    - CMAKE_BUILD_TYPE="Release" WITH_MPI=OFF CXX=g++
    - CMAKE_BUILD_TYPE="Release" WITH_MPI=ON CXX=g++
    - CMAKE_BUILD_TYPE="Debug" WITH_MPI=OFF CXX=clang++
    - CMAKE_BUILD_TYPE="Debug" WITH_MPI=OFF CXX=g++
    - CMAKE_BUILD_TYPE="Debug" WITH_MPI=ON CXX=g++

before_install:
  - sudo add-apt-repository ppa:apokluda/boost1.53 --yes
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes # libstdc++-4.8
  - if [ "${CXX}" == "clang++" ]; then sudo add-apt-repository --yes ppa:h-rayflood/llvm; fi  # clang++-3.2
  - sudo apt-get update


install:
  # note: clang needs g++-4.8 it for libstdc++ update
  - if [ "${CXX}" == "clang++" ]; then sudo apt-get -qq install clang-3.2; fi
  - if [ "${WITH_MPI}" == "ON" ]; then sudo apt-get -qq install mpich2 libmpich2-dev; fi
  - sudo apt-get install g++-4.8 # clang need it for libstdc++ update
  - sudo apt-get install libboost1.53-all-dev libfftw3-3 libfftw3-dev

before_script:
  # update compilers
  - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "${CXX}" == "clang++" ]; then export CXX="clang++-3.2" CC="clang-3.2"; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -Dpfasst_WITH_MPI=${WITH_MPI} -Dpfasst_DISABLE_LIBCXX=ON -Dpfasst_BUILD_TESTS=ON -Dpfasst_BUILD_EXAMPLES=ON ..
  - if [ "${WITH_MPI}" == "ON" ]; then mpicxx --version; fi
  - make
  - make test
  - make run_example_all
