sudo: false
dist: precise

language:
  - cpp

cache:
  - apt

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6
      - doxygen
      - gcc-5
      - g++-5
      - graphviz
      - libfftw3-3
      - libfftw3-dev
      - libeigen3-dev
      - libboost1.55-dev
      - libboost-math1.55-dev
      - libboost-program-options1.55-dev

compiler:
  - gcc
  - clang

env:
  global: 
    - BUILD_DOXYGEN=false
  matrix:
    - CMAKE_BUILD_TYPE=Release
    - CMAKE_BUILD_TYPE=Debug

matrix:
  include:
    - env: BUILD_DOXYGEN=true

install:
  - if [ "${CXX}" == "g++" ]; then
      echo "Using GCC 5" && export CXX="g++-5" CC="gcc-5";
    else
      echo "Using Clang 3.6" && export CXX="clang-3.6" CC="clang-3.6";
    fi

before_script:
  - printenv | sort -u
  - which ${CXX}
  - which ${CC}

script:
  - if [ "${BUILD_DOXYGEN}" == "true" ]; then
      doxygen --version;
      doxygen;
    else
      mkdir build && cd build;
      cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -Dpfasst_WITH_MPI=OFF -Dpfasst_BUILD_TESTS=ON -Dpfasst_BUILD_EXAMPLES=ON -DCMAKE_VERBOSE_MAKEFILE=ON ..;
      make -j2;
      make test;
    fi
